name: Generate Stats Images

on:
  push:
    branches: [ master ]
  #schedule:
  #  - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Checkout history branch
      run: |
        git config --global user.name "pushpakumarbalan/github-stats"
        git config --global user.email "github-stats[bot]@meinic.github.io"
        git pull
        git checkout generated || git checkout -b generated
        git merge master || true

    - uses: mlugg/setup-zig@v2
      with:
        version: master

    - name: Build
      run: zig build --release=fast

    - name: Generate images
      run: |
        mkdir -p generated
        ./zig-out/bin/github-stats \
          --overview-template templates/overview.svg \
          --languages-template templates/languages.svg \
          --overview-output-file generated/overview.svg \
          --languages-output-file generated/languages.svg
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        EXCLUDE_REPOS: ${{ secrets.EXCLUDED }}
        EXCLUDE_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_PRIVATE: "false"
        DEBUG: "false"
        MAX_RETRIES: 5

    - name: Commit to the repo
      run: |
        git add .
        # Force the build to succeed, even if no files were changed
        git commit -m 'Update generated files' || true
        git push --set-upstream origin generated

